import os
import xml.etree.ElementTree as ET

base_path = "/Users/chloepark/Desktop/with-robot-4th/model/robocasa/assets/objects/objaverse"
targets = {
    "apple": "apple_0",
    "banana": "banana_1",
    "bottled_water": "bottled_water_1",
    "can": "can_0",
    "mug": "mug_0"
}

print("<!-- ASSET OBSTACLES: Generated by inspect_assets.py -->")
print("<asset>")

assets_xml = []
bodies_xml = []

for category, subdir in targets.items():
    obj_path = os.path.join(base_path, category, subdir)
    model_xml_path = os.path.join(obj_path, "model.xml")
    
    if not os.path.exists(model_xml_path):
        print(f"<!-- ERROR: {model_xml_path} not found -->")
        continue
        
    try:
        tree = ET.parse(model_xml_path)
        root = tree.getroot()
        assets = root.find("asset")
        
        mesh_name = f"{category}_mesh"
        mat_name = f"{category}_mat"
        tex_name = f"{category}_tex"
        
        # Find the first visual mesh
        found_mesh = False
        if assets is not None:
            for mesh in assets.findall("mesh"):
                file = mesh.get("file")
                # We want the visual mesh, usually has 'vis' or is the first one
                if "vis" in file or "visual" in file:
                    rel_path = f"assets/objects/objaverse/{category}/{subdir}/{file}"
                    scale = mesh.get("scale", "1 1 1")
                    assets_xml.append(f'  <mesh file="{rel_path}" name="{mesh_name}" scale="{scale}"/>')
                    found_mesh = True
                    break
            
            # Find texture if available
            for texture in assets.findall("texture"):
                file = texture.get("file")
                if file:
                    rel_path = f"assets/objects/objaverse/{category}/{subdir}/{file}"
                    assets_xml.append(f'  <texture type="2d" name="{tex_name}" file="{rel_path}"/>')
                    assets_xml.append(f'  <material name="{mat_name}" texture="{tex_name}" specular="0.5" shininess="0.25"/>')
                    break
        
        if found_mesh:
            # Create body definition
            # Positioned far away initially
            body_xml = f"""
    <body name="obstacle_{category}" pos="-100 -100 0">
      <freejoint/>
      <geom name="obstacle_{category}_geom" type="mesh" mesh="{mesh_name}" material="{mat_name}" mass="1.0" friction="0.95 0.3 0.1" solimp="0.998 0.998 0.001" solref="0.001 1" density="100"/>
      <site name="obstacle_{category}_site" pos="0 0 0" size="0.01" rgba="1 0 0 1"/>
    </body>"""
            bodies_xml.append(body_xml)

    except Exception as e:
        print(f"<!-- Error parsing {model_xml_path}: {e} -->")

print("\n".join(assets_xml))
print("</asset>")
print("\n<worldbody>")
print("\n".join(bodies_xml))
print("</worldbody>")
